<?php

use Illuminate\Database\Seeder;

class SectionSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    DB::table('sections')->insert(array(
      array(
        'area_id' => '1',
        'name' => 'hr',
        'title' => '',
        'tealTitle' => 'Human Resources',
        'subTitle' => 'Content Coming Soon',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/hr',
        'landingImage' => '/images/hr-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="https://www.freepik.com/free-photos-vectors/abstract" target="_blank">Abstract vector created by pch.vector - www.freepik.com</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Contact", "color": "grey", "icon": "far fa-address-book", "link": "#"},{"id": "3", "text": "Help", "color": "orange darken-2", "icon": "far fa-question-circle", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
      array(
        'area_id' => '1',
        'name' => 'finance',
        'title' => 'Welcome to',
        'tealTitle' => 'Finance',
        'subTitle' => 'Content Coming Soon',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/finance',
        'landingImage' => '/images/finance-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="https://www.freepik.com/free-photos-vectors/money" target="_blank" >Money vector created by pch.vector - www.freepik.com</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Contact", "color": "grey", "icon": "far fa-address-book", "link": "#"},{"id": "3", "text": "Help", "color": "orange darken-2", "icon": "far fa-question-circle", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
      array(
        'area_id' => '1',
        'name' => 'datamis',
        'title' => '',
        'tealTitle' => 'Data & Information Systems',
        'subTitle' => 'Content Coming Soon',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/datamis',
        'landingImage' => '/images/data-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="https://www.freepik.com/free-photos-vectors/business" target="_blank" >Business vector created by stories - www.freepik.com</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Contact", "color": "grey", "icon": "far fa-address-book", "link": "#"},{"id": "3", "text": "Help", "color": "orange darken-2", "icon": "far fa-question-circle", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
      array(
        'area_id' => '1',
        'name' => 'dataprotection',
        'title' => '',
        'tealTitle' => 'Data Protection',
        'subTitle' => 'Content Coming Soon',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/dataprotection',
        'landingImage' => '/images/dataprotection-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="https://www.freepik.com/free-photos-vectors/card" target="_blank">Card vector created by stories - www.freepik.com</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Contact", "color": "grey", "icon": "far fa-address-book", "link": "#"},{"id": "3", "text": "Help", "color": "orange darken-2", "icon": "far fa-question-circle", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
      array(
        'area_id' => '1',
        'name' => 'ict',
        'title' => 'Welcome to',
        'tealTitle' => 'ICT',
        'subTitle' => 'Content Coming Soon',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/ict',
        'landingImage' => '/images/ict-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="http://www.freepik.com" target="_blank" >Designed by pikisuperstar / Freepik</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Contact", "color": "grey", "icon": "far fa-address-book", "link": "#"},{"id": "3", "text": "Help", "color": "orange darken-2", "icon": "far fa-question-circle", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
      array(
        'area_id' => '1',
        'name' => 'mediaandpr',
        'title' => 'Welcome to',
        'tealTitle' => 'Media & PR',
        'subTitle' => 'Content Coming Soon',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/mediaandpr',
        'landingImage' => '/images/mediapr-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="https://www.freepik.com/free-photos-vectors/people" target="_blank">People vector created by stories - www.freepik.com</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Contact", "color": "grey", "icon": "far fa-address-book", "link": "#"},{"id": "3", "text": "Help", "color": "orange darken-2", "icon": "far fa-question-circle", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
      array(
        'area_id' => '1',
        'name' => 'healthandsafety',
        'title' => '',
        'tealTitle' => 'Health & Safety',
        'subTitle' => 'Content Coming Soon',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/healthandsafety',
        'landingImage' => '/images/healthandsafety-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="http://www.freepik.com" target="_blank">Designed by Freepik</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Contact", "color": "grey", "icon": "far fa-address-book", "link": "#"},{"id": "3", "text": "Help", "color": "orange darken-2", "icon": "far fa-question-circle", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
      array(
        'area_id' => '1',
        'name' => 'premises',
        'title' => 'Welcome to',
        'tealTitle' => 'Premises',
        'subTitle' => 'Content Coming Soon',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/premises',
        'landingImage' => '/images/premises-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="https://www.freepik.com/free-photos-vectors/people" target="_blank" >People vector created by macrovector - www.freepik.com</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Contact", "color": "grey", "icon": "far fa-address-book", "link": "#"},{"id": "3", "text": "Help", "color": "orange darken-2", "icon": "far fa-question-circle", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
      array(
        'area_id' => '2',
        'name' => 'updates',
        'title' => 'Welcome to',
        'tealTitle' => 'Updates',
        'subTitle' => 'Content Coming Soon',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/updates',
        'landingImage' => '/images/updates-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="https://www.freepik.com/free-photos-vectors/technology" target="_blank" >Technology vector created by stories - www.freepik.com</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Button", "color": "grey", "icon": "far fa-star", "link": "#"},{"id": "3", "text": "Button", "color": "orange darken-2", "icon": "fab fa-rebel", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
      array(
        'area_id' => '3',
        'name' => 'policies',
        'title' => 'Welcome to',
        'tealTitle' => 'Policies & Documents',
        'subTitle' => '',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/policies',
        'landingImage' => '/images/policies-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="https://www.freepik.com/free-photos-vectors/technology" target="_blank" >Technology vector created by stories - www.freepik.com</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Button", "color": "grey", "icon": "far fa-star", "link": "#"},{"id": "3", "text": "Button", "color": "orange darken-2", "icon": "fab fa-rebel", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
      array(
        'area_id' => '3',
        'name' => 'calendar',
        'title' => 'Welcome to',
        'tealTitle' => 'Events & Key Dates',
        'subTitle' => '',
        'welcomeSubtext' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit omnis perspiciatis dolor dolorum libero eveniet, officia sint praesentium modi ratione voluptate dolore, provident corporis. Rerum quod error dolor eum numquam!',
        'link' => '/calendar',
        'landingImage' => '/images/events-dates-landing.jpg',
        'landingImageCaption' => '<a class="freepik" href="https://www.freepik.com/free-photos-vectors/calendar" target="_blank" >Calendar vector created by stories - www.freepik.com</a>',
        'buttons' => '[{"id": "1", "text": "Button", "color": "teal", "icon": "fa fa-arrow-right", "link": "#"},{"id": "2", "text": "Button", "color": "grey", "icon": "far fa-star", "link": "#"},{"id": "3", "text": "Button", "color": "orange darken-2", "icon": "fab fa-rebel", "link": "#"}]',
        'actioncards' => '[{"id": "1", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/81.jpg", "icon": "fa-phone", "color": "teal", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "01253 272727"},{"id": "2", "title": "Title Text", "image": "https://randomuser.me/api/portraits/men/2.jpg", "icon": "fa-flag-usa", "color": "orange darken-2", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "contact@teamfcat.co.uk"},{"id": "3","title": "Title Text", "image": "https://randomuser.me/api/portraits/women/81.jpg", "icon": "fa-at", "color": "grey", "text": "Lorem ipsum dolor, sit amet consectetur adipisicing elit.", "chip": "admin@teamfcat.co.uk"}]',
        'active' => '1',
      ),
    ));
  }
}
